/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/g7TyT0RB5Bl
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
} from '@/components/ui/card'
import {
  Table,
  TableHeader,
  TableRow,
  TableHead,
  TableBody,
  TableCell,
} from '@/components/ui/table'
import { Badge } from '@/components/ui/badge'
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuLabel,
  DropdownMenuItem,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
} from '@/components/ui/dropdown-menu'
import { Button } from '@/components/ui/button'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import type { Tenant } from '@/types/tenant'

export default function TenantList({ tenants }: { tenants: Tenant[] }) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Hyresgäster</CardTitle>
        <CardDescription>
          Hantera dina hyresgäster och visa deras information.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="hidden w-[100px] sm:table-cell">
                <span className="sr-only">Bild</span>
              </TableHead>
              <TableHead>Namn</TableHead>
              <TableHead>Email</TableHead>
              <TableHead className="hidden md:table-cell">Telefon</TableHead>
              <TableHead className="hidden md:table-cell">Adress</TableHead>
              <TableHead className="hidden md:table-cell">
                Lägenhetsnummer
              </TableHead>
              <TableHead className="hidden md:table-cell">
                Senaste betalning
              </TableHead>
              <TableHead>
                <span className="sr-only">Åtgärder</span>
              </TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {tenants.map((tenant) => (
              <TableRow key={tenant.id}>
                <TableCell className="hidden sm:table-cell">
                  <Avatar>
                    <AvatarImage src="/new-avatar.svg" alt="Hyresgästbild" />
                    <AvatarFallback>
                      {tenant.name
                        .split(' ')
                        .map((n) => n[0])
                        .join('')}
                    </AvatarFallback>
                  </Avatar>
                </TableCell>
                <TableCell className="font-medium">{tenant.name}</TableCell>
                <TableCell>{tenant.email}</TableCell>
                <TableCell className="hidden md:table-cell">
                  {tenant.phoneNumber}
                </TableCell>
                {!tenant.leases?.length ? (
                  <TableCell colSpan={3} className="text-muted-foreground">
                    Ingen aktivt hyresavtal
                  </TableCell>
                ) : (
                  <>
                    <TableCell className="hidden md:table-cell">
                      {tenant.leases[0]?.address || 'Ingen adress'}
                    </TableCell>
                    <TableCell className="hidden md:table-cell">
                      {tenant.leases[0]?.id || 'Ingen lägenhetsnummer'}
                    </TableCell>
                    <TableCell className="hidden md:table-cell">
                      <Badge className="text-xs" variant="secondary">
                        {tenant.leases[0]?.status || 'Ingen status'}
                      </Badge>
                    </TableCell>
                  </>
                )}
                <TableCell>
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button aria-haspopup="true" size="icon" variant="ghost">
                        <MoveHorizontalIcon className="h-4 w-4" />
                        <span className="sr-only">Öppna meny</span>
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end">
                      <DropdownMenuLabel>Åtgärder</DropdownMenuLabel>
                      <DropdownMenuItem>Visa</DropdownMenuItem>
                      <DropdownMenuItem>Redigera</DropdownMenuItem>
                      <DropdownMenuItem>Säg upp hyresavtal</DropdownMenuItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </CardContent>
      <CardFooter>
        <div className="flex items-center justify-between">
          <div className="text-xs text-muted-foreground">
            Visar <strong>1-4</strong> av <strong>4</strong> hyresgäster
          </div>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline" className="gap-1">
                <ArrowUpDownIcon className="w-4 h-4" />
                Sortera efter
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="w-[200px]">
              <DropdownMenuRadioGroup>
                <DropdownMenuRadioItem value="namn">Namn</DropdownMenuRadioItem>
                <DropdownMenuRadioItem value="adress">
                  Adress
                </DropdownMenuRadioItem>
                <DropdownMenuRadioItem value="lägenhetsnummer">
                  Lägenhetsnummer
                </DropdownMenuRadioItem>
                <DropdownMenuRadioItem value="senaste_betalning">
                  Senaste betalning
                </DropdownMenuRadioItem>
              </DropdownMenuRadioGroup>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </CardFooter>
    </Card>
  )
}

function ArrowUpDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m21 16-4 4-4-4" />
      <path d="M17 20V4" />
      <path d="m3 8 4-4 4 4" />
      <path d="M7 4v16" />
    </svg>
  )
}

function MoveHorizontalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="18 8 22 12 18 16" />
      <polyline points="6 8 2 12 6 16" />
      <line x1="2" x2="22" y1="12" y2="12" />
    </svg>
  )
}
